name: ci
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        env:
          BUILD_ENV: ci
        run: |
          npm install
          npm run build

      - name: Test
        run: |
          npm run test

      - name: Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
